apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-solr
  name: {{ .Release.Name }}-solr
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Release.Name }}-solr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-solr
    spec:
      containers:
      - args:
        - solr-precreate
        - tess
        - /opt/solr/server/solr/configsets/production
        image: solr:8
        imagePullPolicy: IfNotPresent
        name: {{ .Release.Name }}-solr
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/solr
          name: solr-data
        - mountPath: /opt/solr/server/solr/configsets/production/conf
          name: solr-claim
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: solr-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-solr-data
      - configMap:
          defaultMode: 420
          name: {{ .Release.Name }}-solr-claim
        name: solr-claim
status: {}
