apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-tess
spec:
  port:
    targetPort: 3000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ .Release.Name }}-tess
    weight: 100
  wildcardPolicy: None
status: {}
