apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-tess
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: {{ .Release.Name }}-tess
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
