apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-solr
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8983
    protocol: TCP
    targetPort: 8983
  selector:
    app: {{ .Release.Name }}-solr
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
